Added UI for error handling, added Alert component
blkflower/pitaka-frontend pull request #5
Opened 2023-10-24 14:17 UTC by japhethbalane

![Screenshot from 2023-10-24 22-16-16](https://github.com/blkflower/pitaka-frontend/assets/13504076/24123f34-ff95-46e4-bb19-bba38457a87c)
![Screenshot from 2023-10-24 22-16-31](https://github.com/blkflower/pitaka-frontend/assets/13504076/777af8ab-d580-44a2-b8f8-246295074928)
![Screenshot from 2023-10-24 22-16-47](https://github.com/blkflower/pitaka-frontend/assets/13504076/9b255709-0b93-481d-b522-1c30acc287c0)

2023-10-24 14:36 UTC, balanejacob reviewed
@japhethbalane i think it is better if the label "Email address" and the Alert component will be aligned with the input field and button like this:
![Screenshot 2023-10-24 223215](https://github.com/blkflower/pitaka-frontend/assets/61689264/9de42cef-d1e9-40e4-8d1c-e977915baa48)

2023-10-25 06:59 UTC, arnellebalane requested changes

2023-10-25 06:59 UTC, arnellebalane commented on src/lib/components/Alert.svelte
> +  export let type: 'info' | 'success' | 'warning' | 'error' = 'info';
@japhethbalane Declare these individual values in a separate TS type.

2023-10-25 06:59 UTC, arnellebalane commented on src/lib/components/Button.svelte
> +	disabled={$$props.disabled}>{label}</button
@japhethbalane Don't abuse the `$$props` variable let's only use it for classes for now. The `disabled` prop should be defined as a separate variable. The reason why we can't declare `class` as a separate prop is because `class` is a reserved keyword in JS. All other props should be declared.

2023-10-25 06:59 UTC, arnellebalane commented on tailwind.config.js
>  				primaryText: '#1E293B'
@japhethbalane All of these colors are already predefined in Tailwind so no need to redefine them https://tailwindcss.com/docs/customizing-colors

2023-10-28 07:10 UTC, arnellebalane approved these changes

2023-10-30 07:00 UTC, merged